chore: upgrade to cdktf 0.17 and tsx
cdktf/cdktf-repository-manager pull request #199
Opened 2023-06-15 14:29 UTC by DanielMSchmidt

2023-06-15 14:39 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-GgzXoSSqU7dSXbfw" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/c13f6b68-e709-4870-8748-58c1c1d505e1/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-GgzXoSSqU7dSXbfw

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 1s [id=cdktf-cdk8s]
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 2s [id=cdktf-multi-stack-tfe]
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 1s [id=cdktf-tf-module-stack]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 1s [id=cdktf-local-exec]
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-multi-stack-tfe_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_5BED1C4A will be created
  + resource "gi [...]

2023-06-15 14:39 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-mz9FJjVnpFsPkEbQ" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/57522d44-b112-4d49-97fc-d4f3a3ad65cf/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-mz9FJjVnpFsPkEbQ

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 5s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_1B9B597E will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_1B9B597E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_8FE34BA4 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_8FE34BA4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-gh-token_6F32D8A9 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-gh-token_6F32D8A9" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-maven-gpg-private-key-passphrase_64B68B77 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-maven-gpg-private-key-passphrase_64B68B77" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-maven-gpg-private-key_CE85BAE4 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-maven-gpg-private-key_CE85BAE4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-maven-password_95B7424C will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-maven-password_95B7424C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-maven-staging-profile-id_7A0DF91E will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-maven-staging-profile-id_7A0DF91E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-maven-username_553FE0BE will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-maven-username_553FE0BE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-npm-token_1689F3C4 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-npm-token_1689F3C4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-nuget-api-key_404500D3 will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-nuget-api-key_404500D3" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-twine-password_C2DE8DEF will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-twine-password_C2DE8DEF" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-twine-username_CFC0E61E will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-twine-username_CFC0E61E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-mongodbatlas"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretalertprsslackwebhookurl_27DBACFE will be destroyed
  # (because github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretalertprsslackwebhookurl_27D [...]

2023-06-15 14:40 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-SXpEsMVrNJXh5hYA" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/113e151e-498f-4f34-a848-163278fede68/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-SXpEsMVrNJXh5hYA

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 5s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token_3A5BB55D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token_3A5BB55D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-password_8161FA07 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-password_8161FA07" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-username_FEC3D682 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-username_FEC3D682" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-npm-token_361A8BEA will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-npm-token_361A8BEA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-password_E7E53B1D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-password_E7E53B1D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765 will be created
  + resource "github_actions_secret" "cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-azurestack"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-gh-token-alias-GO_GITHU [...]

2023-07-05 08:24 UTC, mutahhir requested changes
Blocking this since the diff seems to have a lot of delete & creates. @DanielMSchmidt is this expected?

2023-07-05 08:24 UTC, mutahhir commented on lib/repository.ts
> +import { GithubProvider } from "@cdktf/provider-github/lib/provider";
❤️

2023-07-05 08:24 UTC, mutahhir commented on package.json
> +    "@cdktf/provider-github": "^9.0.0",
❤️

2023-08-25 09:49 UTC, xiehan commented
One thing that could be related is that we hard-code a very old version of the underlying GitHub provider here:

https://github.com/cdktf/cdktf-repository-manager/blob/9fe187173e3f34b8ceeedb318e9cdc367a4831d6/main.ts#L364-L365

I suspect that may also need to be updated. I ran into this in #213 as well.

2023-09-01 09:28 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-YXv3D6sEZefDjEtP" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/e3c40705-c119-4d94-ab38-c5c2b93b4e2b/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-YXv3D6sEZefDjEtP

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 1s [id=cdktf-tf-module-stack]
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 1s [id=cdktf-multi-stack-tfe]
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 2s [id=cdktf-cdk8s]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 2s [id=cdktf-local-exec]
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-multi-stack-tfe_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_5BED1C4A will be created
  + resource "gi [...]

2023-09-01 09:29 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-sMo2Z8LDr17YFb3C" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/c0b0598c-37dd-464f-b0b2-a3074aee3660/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-sMo2Z8LDr17YFb3C

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token_85560652 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token_85560652" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B" {
     [...]

2023-09-01 09:30 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-1yHdR6CjkBBqbD1C" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/e44a0c5c-71c9-4d55-b1e8-02fa1a1e3cb8/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-1yHdR6CjkBBqbD1C

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token_3A5BB55D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token_3A5BB55D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-password_8161FA07 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-password_8161FA07" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-username_FEC3D682 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-username_FEC3D682" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-npm-token_361A8BEA will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-npm-token_361A8BEA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-password_E7E53B1D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-password_E7E53B1D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765 will be created
  + resource "github_actions_secret" "cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-azurestack"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-gh-token-alias-GO_GITHU [...]

2023-09-01 09:31 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-CjbRoWYoQXUudfF7" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/6b96629d-1b21-42ef-abc3-fbcdb7214609/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-CjbRoWYoQXUudfF7

Waiting for the plan to start...

Terraform v1.0.7
on linux_amd64
Initializing plugins and modules...

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # github_repository.repos_cdktfprovideropentelekomcloud_repo_8ABA825B has been changed
  ~ resource "github_repository" "repos_cdktfprovideropentelekomcloud_repo_8ABA825B" {
      ~ etag                   = "W/\"49646b8999464cf019bf4b8fd0b2c017ea144d1746586f0f196d7c999cf307ed\"" -> "W/\"f6d3f08a949b7446ca777cd5f3360fd4e81cfd7c0d7c317809b8549a2abe7ce3\""
        id                     = "cdktf-provider-opentelekomcloud"
        name                   = "cdktf-provider-opentelekomcloud"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfprovidersnowflakego_repo_82DE7E70 has been changed
  ~ resource "github_repository" "repos_cdktfprovidersnowflakego_repo_82DE7E70" {
      ~ etag                   = "W/\"28d1461aab83a3943c19d09bbc2b79f6e3db00cf98f73d02da6f8b81988a9605\"" -> "W/\"5e6b99d6fad7c228a0fc0cc06bbd85c3cf67aa3df50c6def0fff07d071732eb6\""
        id                     = "cdktf-provider-snowflake-go"
        name                   = "cdktf-provider-snowflake-go"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderokta_repo_BB6AE56D has been changed
  ~ resource "github_repository" "repos_cdktfproviderokta_repo_BB6AE56D" {
      ~ etag                   = "W/\"e872ea089f45823bb0debc0b67ff8c7014f6dadaeec51987e87d63045391bac6\"" -> "W/\"1c529cd5874106a2558505044da2aa1a5150a8fb22a9aa2a0148b76b0a559274\""
        id                     = "cdktf-provider-okta"
        name                   = "cdktf-provider-okta"
        # (26 unchanged attributes hidden)
    }
  # github_team_repository.repos_cdktfprovidervaultgo_repositorysetup_managingteam_3D03CE6E has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidervaultgo_repositorysetup_managingteam_3D03CE6E" {
      ~ etag       = "W/\"25f8229f7aa1621f00cbc9dba4833002c4b24d20751cd639a2e22bb5b39621f6\"" -> "W/\"d2829593f64e62f0e5321f88107398cc4b9cdc512bac60759dd81bf92dd5c63a\""
        id         = "6602018:cdktf-provider-vault-go"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderdockergo_repo_B68835EA has been changed
  ~ resource "github_repository" "repos_cdktfproviderdockergo_repo_B68835EA" {
      ~ etag                   = "W/\"64e439b5f51e9d1f4b22ecbc5961c5b8b10a69188a77c28ee4a729c41e92dea3\"" -> "W/\"6e21b73abd5a89453340d119bcd96dd3d6a3dc3677ef4cc87fe120874bc0d25d\""
        id                     = "cdktf-provider-docker-go"
        name                   = "cdktf-provider-docker-go"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfrepositorymanager_repo_9D19EE52 has been changed
  ~ resource "github_repository" "repos_cdktfrepositorymanager_repo_9D19EE52" {
      ~ etag                   = "W/\"1a4df665ebec0b0dbad5fe65c6808bb3107f5e8bbdc4a0fa5eb527eadab394a3\"" -> "W/\"6df875e172d04cc8bc1d512c8344b82315488ecbc9876f52c777a5c655de5750\""
        id                     = "cdktf-repository-manager"
        name                   = "cdktf-repository-manager"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderhashicups_repo_DC950547 has been changed
  ~ resource "github_repository" "repos_cdktfproviderhashicups_repo_DC950547" {
      ~ etag                   = "W/\"3c88dd4a09ab1549943d2e58b3fe0679956da859b9b119e64151001bd569745b\"" -> "W/\"2b8907f0651c641cb7246894bd1b1e040eaa46c469471107bf4695b30e225acd\""
        id                     = "cdktf-provider-hashicups"
        name                   = "cdktf-provider-hashicups"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderhelm_repo_E5C9B6C8 has been changed
  ~ resource "github_repository" "repos_cdktfproviderhelm_repo_E5C9B6C8" {
      ~ etag                   = "W/\"0c47eb0e8e089636a1b290c0d34f0730cfad645caf9107b30d49d42e3d1114d2\"" -> "W/\"445a74c7d8a0139ee7380118422123c1b1df19fc4e2a83493264b3fdc64e0972\""
        id                     = "cdktf-provider-helm"
        name                   = "cdktf-provider-helm"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderazurermgo_repo_08A9904C has been changed
  ~ resource "github_repository" "repos_cdktfproviderazurermgo_repo_08A9904C" {
      ~ etag                   = "W/\"c60471d7e66e76a80118af365dfbfe984c79ad9b56b3857b56aa235383338789\"" -> "W/\"24c4bfb6ef9ae62e2dd5312965039ed853905c91d7a881b37c511e2151040edd\""
        id                     = "cdktf-provider-azurerm-go"
        name                   = "cdktf-provider-azurerm-go"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfprovidersnowflake_repo_483928D8 has been changed
  ~ resource "github_repository" "repos_cdktfprovidersnowflake_repo_483928D8" {
      ~ etag                   = "W/\"30f73ddf20a632e5256f92cab4880e0c9976485bfdfe3129f9363d3808b88950\"" -> "W/\"f30be89d914a8848b21031ae0a0b0e76457ffc107f7b6a286f99bfc5d6700880\""
        id                     = "cdktf-provider-snowflake"
        name                   = "cdktf-provider-snowflake"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderawsgo_repo_AE367E97 has been changed
  ~ resource "github_repository" "repos_cdktfproviderawsgo_repo_AE367E97" {
      ~ etag                   = "W/\"82559e2448b4fb1699cbee0422b3839817e1053e36b236d82a81f9afbed29fcc\"" -> "W/\"a8c0bf73de2e08e20104a28f60dbc5b2b25ef272b7ed0d3e58ec51cd866558cd\""
        id                     = "cdktf-provider-aws-go"
        name                   = "cdktf-provider-aws-go"
        # (26 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfprovidervault_repo_CDB996AE has been changed
  ~ resource "github_repository" "repos_cdktfprovidervault_repo_CDB996AE" {
      ~ etag                   = "W/\"87f7d91dd2089fc5839ad94d774ffd7a486e5ea26c701148b272199163554564\"" -> "W/\"87ab9f0d1286cf3c3e75b4853a429395cceb0a36e0003b1016ce1a12012571ac\""
        id                     = "cdktf-provider-vault"
        name                   = "cdktf-provider-vault"
        # (26 unchanged attributes hidden)
    }
  # github_team_repository.repos_cdktfprovidertlsgo_repositorysetup_managingteam_E1E51A55 has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidertlsgo_repositorysetup_managingteam_E1E51A55" {
      ~ etag       = "W/\"090c71eb152f256cb6ea889f6df3d422238fd709fc8d2edfcd60d3be28967005\"" -> "W/\"03a92c5fe6fdd987d846ce1fc56bef09335d87d2805e2acad34d2d2beeeb6987\""
        id         = "6602018:cdktf-provider-tls-go"
        # (3 unchanged attributes hidden)
    }
  # github_team_repository.repos_cdktfprovidergooglego_repositorysetup_managingteam_20D524CA has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidergooglego_repositorysetup_managingteam_20D524CA" {
      ~ etag       = "W/\"398f1919ee0ab6a3add4fd8eb6b36c964304206ad906ee728e71b9639df82446\"" -> "W/\"3b9018f66c128fe4b1abf73332fb475b48dd33fd5d069cf57f6e569caa38b122\""
        id         = "6602018:cdktf-provider-google-go"
        # (3 unchanged attributes hidden)
    }
  # github_team_repository.repos_cdktfprov [...]

2023-09-01 09:32 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-kQbfgbiTYYECQHQt" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/edd5f4cc-9c4b-41c0-bbb5-6d8b798ed001/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-kQbfgbiTYYECQHQt

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 5s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token_85560652 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token_85560652" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B" {
     [...]

2023-09-01 09:32 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-3JbAewvqqBcpE1tR" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/65c2c7e8-8d2c-405a-8dcb-9ace776040c7/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-3JbAewvqqBcpE1tR

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 2s [id=cdktf-multi-stack-tfe]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 1s [id=cdktf-cdk8s]
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 2s [id=cdktf-tf-module-stack]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 1s [id=cdktf-local-exec]
data.github_team.cdktf-team-cdktf: Read complete after 6s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-multi-stack-tfe_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_5BED1C4A will be created
  + resource "gi [...]

2023-09-01 09:33 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-mgMn2Tf3FwFu69aR" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/837f669a-32c3-4545-96f9-c4dfc9da15c8/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-mgMn2Tf3FwFu69aR

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token_3A5BB55D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token_3A5BB55D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-password_8161FA07 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-password_8161FA07" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-username_FEC3D682 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-username_FEC3D682" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-npm-token_361A8BEA will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-npm-token_361A8BEA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-password_E7E53B1D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-password_E7E53B1D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765 will be created
  + resource "github_actions_secret" "cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-azurestack"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-gh-token-alias-GO_GITHU [...]

2023-09-01 09:34 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-w9AjRpR7d4xP63xQ" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/6754b51a-2a55-428f-b76b-7dabcea42728/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-w9AjRpR7d4xP63xQ

Waiting for the plan to start...

Terraform v1.0.7
on linux_amd64
Initializing plugins and modules...

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # github_team_repository.repos_cdktfprovidercloudflarego_repositorysetup_managingteam_D3449EB2 has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidercloudflarego_repositorysetup_managingteam_D3449EB2" {
      ~ etag       = "W/\"43e871d987bc76de82305a5b2a690e8b048e46f8c646766392a2bf1411cd1c1c\"" -> "W/\"acafe4b80218c1117dfcf51f40cf5875820dac9ebf7ac2dfcde9caee4a061682\""
        id         = "6602018:cdktf-provider-cloudflare-go"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderpagerduty_repo_0AF36FE3 has been changed
  ~ resource "github_repository" "repos_cdktfproviderpagerduty_repo_0AF36FE3" {
      + allow_auto_merge            = true
      + allow_update_branch         = false
      ~ etag                        = "W/\"ab036d647fa0131ee8ac6dff7b63a61b5250509490b500635381e3283dc2cde9\"" -> "W/\"602f15a7b30157e8f89f6bebac4ed4b6fd17a3cfbdbc7836e23369006f881f36\""
      + has_discussions             = false
        id                          = "cdktf-provider-pagerduty"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-pagerduty"
      + primary_language            = "TypeScript"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_issue_label.repos_cdktfproviderdatabricks_repositorysetup_automergelabel_728B6C30 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderdatabricks_repositorysetup_automergelabel_728B6C30" {
      ~ etag       = "W/\"7044f381221ede7e20421c0d95ef6757e37475a7dd0138a4a402b53e110f6179\"" -> "W/\"f2130cce0db63e7a26bf8bac5b244e0b1324f7e0aa816b46eea13fadb09eb2bc\""
        id         = "cdktf-provider-databricks:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfproviderproject_repositorysetup_automergelabel_A38ED365 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderproject_repositorysetup_automergelabel_A38ED365" {
      ~ etag       = "W/\"6f3e90c12531da8b78afef144dbc10da2dfc5592c9fbcdcc9dcf91cbfd677dcc\"" -> "W/\"16debbd12b19b0bf59408a0301d1267f867237269f7dc36cda7162666d5bb32b\""
        id         = "cdktf-provider-project:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfproviderrandomgo_repositorysetup_automergelabel_0A6D2FF6 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderrandomgo_repositorysetup_automergelabel_0A6D2FF6" {
      ~ etag       = "W/\"bce61d1d38bcff00267f06873301853e334e68ad7d44b2d18fd50fa13f093870\"" -> "W/\"4f3dbdca8cbc31c735716e23825316a4eaecc7e1bb289e6a7b2bb1ec28d95565\""
        id         = "cdktf-provider-random-go:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_team_repository.repos_cdktfprovidertemplate_repositorysetup_managingteam_4C76673E has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidertemplate_repositorysetup_managingteam_4C76673E" {
      ~ etag       = "W/\"3ceafc9346c6cfc50387d8806456a256ed2bb788cacdf78641e27f3575186783\"" -> "W/\"67ca85a919adfb2915fddaabfd11dd29faac84c482e0397487a7d441ffc0f9ad\""
        id         = "6602018:cdktf-provider-template"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderspotinstgo_repo_61D25AF8 has been changed
  ~ resource "github_repository" "repos_cdktfproviderspotinstgo_repo_61D25AF8" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"1b3c8d5ac1e4435ff69f52fa2fb4180512ff697bd41c0b774ae849c3cf4cdb70\"" -> "W/\"fd3ec935fd5d68bce31d87f25a1acbc41b651a1bba42934f9f14e68c9fc8d42d\""
      + has_discussions             = false
        id                          = "cdktf-provider-spotinst-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-spotinst-go"
      + primary_language            = "Go"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_team_repository.repos_cdktfproviderdatabricks_repositorysetup_managingteam_8D34FFE1 has been changed
  ~ resource "github_team_repository" "repos_cdktfproviderdatabricks_repositorysetup_managingteam_8D34FFE1" {
      ~ etag       = "W/\"1528588f91ab28c34a0a096f0fc52943f57dcb76b03728aa940501379287ce38\"" -> "W/\"1293cb41c5f9205ae05634f59c8bd6507f664e959ac99e19dffcb0e27203bfea\""
        id         = "6602018:cdktf-provider-databricks"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderexternalgo_repo_3DDBC8C1 has been changed
  ~ resource "github_repository" "repos_cdktfproviderexternalgo_repo_3DDBC8C1" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"4f25a0d80250b2a7cd0300c56a73b41972c366629d507395266954448e86034d\"" -> "W/\"cee36317ef93297c9cbb9983a80d7ecc132c9645850a9d397fbbfd633ac7d729\""
      + has_discussions             = false
        id                          = "cdktf-provider-external-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-external-go"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_repository.repos_cdktfprovidernullgo_repo_1E975951 has been changed
  ~ resource "github_repository" "repos_cdktfprovidernullgo_repo_1E975951" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"56bd6e15382685fc9d5bcd14d7cc576b105671b685ced86999c7cdebf160eb8d\"" -> "W/\"cc81058c7015d16dc8870363f52bf21e1e75806f49360c0bf40c4c485dadac71\""
      + has_discussions             = false
        id                          = "cdktf-provider-null-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name [...]

2023-09-01 09:39 UTC, DanielMSchmidt commented
@xiehan The problem is the removal of our [feature flags](https://developer.hashicorp.com/terraform/cdktf/release/upgrade-guide-v0-17#removal-the-feature-flags-that-go-into-the-context-field-of-the-cdktf-json-file-were-removed) leading to the old syntax (e.g. `github_repository.reposofficialnew_cdktfproviderwaypointgo_repo_A9252B7B`) is replaced with the new,  better to read syntax (e.g. `github_repository.cdktf-provider-waypoint-go_repo_3CFF9EDE`) causing all the recreations.

I'm going to pull the functionality we removed out into a function and set a fixed logical ID based on it for now, we can migrate the state once we have move blocks, but doing it by hand now across 3 stacks would be too cumbersome.

2023-09-01 09:51 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-avFJp2CXtq57bX89" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/907e5e21-cc1c-4398-8aa9-a8cf709789b0/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-avFJp2CXtq57bX89

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 1s [id=cdktf-multi-stack-tfe]
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 2s [id=cdktf-cdk8s]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 2s [id=cdktf-local-exec]
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 1s [id=cdktf-tf-module-stack]
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E3BEFE91" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_99DCA853" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_FDFB28D6" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_C93B326E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_A6335EE5" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_EF6824FB" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D8006675" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_673FEB36" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-gh-token_83854260" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-npm-token_668831D4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-password_92687429" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06 will be created
  + resource "github_actions_secret" "cdktf-construct-cdktf-local-exec_repo_secret-twine-username_740C2F06" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-construct-cdktf-multi-stack-tfe_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_5BED1C4A will be created
  + resource "gi [...]

2023-09-01 09:51 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-CinWEbuR3usDC8Bg" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/1091f96a-1502-4a28-acfb-2e3243439491/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-CinWEbuR3usDC8Bg

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_5DE6A783" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_6A5F0817" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_042F7D01" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-gh-token_85560652 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-gh-token_85560652" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_F7104486" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_C1E80DCE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-password_503A29DE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_9B871CBC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-maven-username_244E333C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-npm-token_2815257C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-nuget-api-key_2B54AA56" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79 will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-password_5E892A79" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA will be created
  + resource "github_actions_secret" "cdktf-provider-launchdarkly_repo_secret-twine-username_2ED8E9BA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B will be created
  + resource "github_actions_secret" "cdktf-provider-mongodbatlas_repo_secret-alert-prs-slack-webhook-url_A0CA0B2B" {
     [...]

2023-09-01 09:52 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-5fRuT9NsWF85USBm" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/3131efd2-53d6-46b8-811d-e2598cf533eb/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-5fRuT9NsWF85USBm

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_27B42B43" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_D4F19919" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_C3F53483" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-gh-token_3A5BB55D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-gh-token_3A5BB55D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_3261C230" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-gpg-private-key_D4B79570" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-password_8161FA07 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-password_8161FA07" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-staging-profile-id_A4B77CAC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-maven-username_FEC3D682 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-maven-username_FEC3D682" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-npm-token_361A8BEA will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-npm-token_361A8BEA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-nuget-api-key_67BBC68E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-password_E7E53B1D will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-password_E7E53B1D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7 will be created
  + resource "github_actions_secret" "cdktf-provider-ad_repo_secret-twine-username_FDEA8ED7" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765 will be created
  + resource "github_actions_secret" "cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_3AAD6765" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-azurestack"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.cdktf-provider-azurestack_repo_secret-gh-token-alias-GO_GITHU [...]

2023-09-01 09:53 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-XMJPCEmXhBN2YGVE" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/1e13270c-b36a-4082-93c5-6516f9109375/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-XMJPCEmXhBN2YGVE

Waiting for the plan to start...

Terraform v1.0.7
on linux_amd64
Initializing plugins and modules...

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # github_repository.repos_cdktfproviderdigitaloceango_repo_728D6E98 has been changed
  ~ resource "github_repository" "repos_cdktfproviderdigitaloceango_repo_728D6E98" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"9377a423c2b5bc5fa653e9523654e282e028b8928e9341c4110c79e596f9ce8d\"" -> "W/\"874b1b75d9f75c21925a18ed259f4c2a83e92c824bfcbdca915ba12e6964c12a\""
      + has_discussions             = false
        id                          = "cdktf-provider-digitalocean-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-digitalocean-go"
      + primary_language            = "Go"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_team_repository.repos_cdktfprovidergooglebetago_repositorysetup_managingteam_D83EF40E has been changed
  ~ resource "github_team_repository" "repos_cdktfprovidergooglebetago_repositorysetup_managingteam_D83EF40E" {
      ~ etag       = "W/\"ff4cb6dbd8cf21cb85efd366d5584b41b1bd3d952d6c0adbe8432fa906ac2d0b\"" -> "W/\"b83b7f55cd320bf9e349e8f836e7ddfa68a0d7b56fe5a796b57fbeb73af35705\""
        id         = "6602018:cdktf-provider-googlebeta-go"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfproviderdocker_repositorysetup_automergelabel_BF5FFDE6 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderdocker_repositorysetup_automergelabel_BF5FFDE6" {
      ~ etag       = "W/\"9451e5b6c721272732c28b59e6512f2d8863f5252a980d90b2bfec8e530529e1\"" -> "W/\"e2959e106c50946f0ad403b46362a842d486a9c83d9e5c48dd461160580a8dee\""
        id         = "cdktf-provider-docker:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfprovidergoogle_repo_3D7769E0 has been changed
  ~ resource "github_repository" "repos_cdktfprovidergoogle_repo_3D7769E0" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"a3febb93e8c1a969671ca037a7d5ff379512a2421f2d4e59b3e51d31f6edfe28\"" -> "W/\"e25a1c8a116ddd2c2ed236e3728774bf6330d3714f3af4e4164403d3be9640a1\""
      + has_discussions             = false
        id                          = "cdktf-provider-google"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-google"
      + primary_language            = "TypeScript"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_branch_protection.repos_cdktfproviderspotinst_repositorysetup_mainprotection_3226E569 has been changed
  ~ resource "github_branch_protection" "repos_cdktfproviderspotinst_repositorysetup_mainprotection_3226E569" {
      + blocks_creations                = false
      + force_push_bypassers            = []
        id                              = "BPR_kwDOHUaHk84B070R"
      + lock_branch                     = false
      + require_conversation_resolution = false
      + required_linear_history         = false
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
  # github_repository.repos_cdktfprovidergooglebetago_repo_2FB8C0AA has been changed
  ~ resource "github_repository" "repos_cdktfprovidergooglebetago_repo_2FB8C0AA" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"57b518200ad93b0d826ad5be129c8fa731f8af606170b2533ed2107d979e8218\"" -> "W/\"2ed6f1c70df9c3e4c3c90ddbb2669992b9065c4696d4575229df9e05b7465620\""
      + has_discussions             = false
        id                          = "cdktf-provider-googlebeta-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-googlebeta-go"
      + primary_language            = "Go"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_repository.repos_cdktfprovidergooglego_repo_D075E66D has been changed
  ~ resource "github_repository" "repos_cdktfprovidergooglego_repo_D075E66D" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"1e42cbeb07a14435f0470f266cbeeb6341d63e73ac57537e56df7e602c05ed69\"" -> "W/\"fc29aa60e66aa111943bd489032d2cdb3df69405c527ef40496351a2917190e2\""
      + has_discussions             = false
        id                          = "cdktf-provider-google-go"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-google-go"
      + primary_language            = "Go"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_issue_label.repos_cdktfprovidergooglebetago_repositorysetup_automergelabel_6E65DD47 has been changed
  ~ resource "github_issue_label" "repos_cdktfprovidergooglebetago_repositorysetup_automergelabel_6E65DD47" {
      ~ etag       = "W/\"2d163591aee7fcabcc48b5f920a2a0cc6d0072b10fb58b089860abc3531240cf\"" -> "W/\"4b921f5a01c9a48ca2b666f97a0d31f37b95ccf965e6abf1377c984203e1a660\""
        id         = "cdktf-provider-googlebeta-go:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderazurerm_repo_19E06DC3 has been changed
  ~ resource "github_repository" "repos_cdktfproviderazurerm_repo_19E06DC3" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"a502249a33a22e6eca01e215cb01e9a6dc72b03bb2144d67f432cfafe106c [...]

2023-09-01 10:12 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-Dm6kBzfQCwWSjdDP" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/bdfd1400-5b49-469a-864e-067f4dbc67ff/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-Dm6kBzfQCwWSjdDP

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 1s [id=cdktf-tf-module-stack]
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 1s [id=cdktf-multi-stack-tfe]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 1s [id=cdktf-local-exec]
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 1s [id=cdktf-cdk8s]
data.github_team.cdktf-team-cdktf: Read complete after 4s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_685F1BFC will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_685F1BFC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_E3B90B5F will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_E3B90B5F" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_15793D0C will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-gh-token_15793D0C" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_E84D4D40 will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-npm-token_E84D4D40" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_3EEB468D will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-twine-password_3EEB468D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_2CE61A73 will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-cdk8s_repo_secret-twine-username_2CE61A73" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-cdk8s"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_CF3E4145 will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_CF3E4145" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_AAB6222D will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_AAB6222D" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token_74A03037 will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-gh-token_74A03037" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-npm-token_C8A5F85E will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-npm-token_C8A5F85E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-twine-password_01F20187 will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-twine-password_01F20187" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-local-exec"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-twine-username_F630C71D will be created
  + resource "github_actions_secret" "custom-constructs_cdktf-construct-cdktf-local-exec_repo_secret-twine-username_F630C [...]

2023-09-01 10:12 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-1E9VZyjnoiLMQ1am" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/40cc5a7e-03b7-49b5-bcfa-23d1a887e50b/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-1E9VZyjnoiLMQ1am

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 3s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_99526CD8 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-alert-prs-slack-webhook-url_99526CD8" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E643F160 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_E643F160" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_D014A00B will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_D014A00B" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token_B076E5A5 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-gh-token_B076E5A5" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_416CB401 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key-passphrase_416CB401" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_43CD5933 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-gpg-private-key_43CD5933" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-password_B811F8CB will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-password_B811F8CB" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_919B2A41 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-staging-profile-id_919B2A41" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-username_6CBB637A will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-maven-username_6CBB637A" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-npm-token_55C9B1E4 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-npm-token_55C9B1E4" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-nuget-api-key_A8CFC2DD will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-nuget-api-key_A8CFC2DD" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-twine-password_F4217409 will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-twine-password_F4217409" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-launchdarkly"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-partners_cdktf-provider-launchdarkly_repo_secret-twine-username_EC15FA2E will be created
  + resource "github_actions_secret" "repos-partners_cdktf-provider-launchdarkly_repo_secret-twine-username_EC15FA2E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
    [...]

2023-09-01 10:13 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-PojY1KeESCLEFtGi" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/d25738c8-5c8e-438d-a1e3-8de848f69644/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-PojY1KeESCLEFtGi

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 7s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_FE138519 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-alert-prs-slack-webhook-url_FE138519" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "ALERT_PRS_SLACK_WEBHOOK_URL"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_3354AFF2 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-gh-token-alias-GO_GITHUB_TOKEN_3354AFF2" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GO_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_EBE245CC will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-gh-token-alias-PROJEN_GITHUB_TOKEN_EBE245CC" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "PROJEN_GITHUB_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-gh-token_2A73F8CA will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-gh-token_2A73F8CA" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "GH_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_4232A6CE will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-maven-gpg-private-key-passphrase_4232A6CE" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY_PASSPHRASE"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-maven-gpg-private-key_6228FF61 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-maven-gpg-private-key_6228FF61" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_GPG_PRIVATE_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-maven-password_560FE18E will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-maven-password_560FE18E" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-maven-staging-profile-id_B61AEF1F will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-maven-staging-profile-id_B61AEF1F" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_STAGING_PROFILE_ID"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-maven-username_589BD3DF will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-maven-username_589BD3DF" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "MAVEN_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-npm-token_2FE1C3B3 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-npm-token_2FE1C3B3" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NPM_TOKEN"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-nuget-api-key_E49C1256 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-nuget-api-key_E49C1256" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "NUGET_API_KEY"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-twine-password_B007A91B will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-twine-password_B007A91B" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_PASSWORD"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-ad_repo_secret-twine-username_29CFF4D8 will be created
  + resource "github_actions_secret" "repos-official-new_cdktf-provider-ad_repo_secret-twine-username_29CFF4D8" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "cdktf-provider-ad"
      + secret_name     = "TWINE_USERNAME"
      + updated_at      = (known after apply)
    }

  # github_actions_secret.repos-official-new_cdktf-provider-azurestack_repo_secret-alert-prs-slack-webhook-url_F284DD90 will  [...]

2023-09-01 10:29 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`failure`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-jUEJt2YQpJa8dtvb" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/23af56fd-8bdc-49d7-9b62-8581b9661f2a/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-jUEJt2YQpJa8dtvb

Waiting for the plan to start...

Terraform v1.0.7
on linux_amd64
Initializing plugins and modules...
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-opentelekomcloud/actions/secrets/TWINE_USERNAME: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-archive/actions/secrets/MAVEN_GPG_PRIVATE_KEY_PASSPHRASE: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-hashicups: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-vault/hooks/387362671: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-datadog/actions/secrets/PROJEN_GITHUB_TOKEN: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-azurerm/actions/secrets/MAVEN_USERNAME: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-snowflake/actions/secrets/NUGET_API_KEY: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-azurerm/actions/secrets/MAVEN_STAGING_PROFILE_ID: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-datadog/actions/secrets/MAVEN_GPG_PRIVATE_KEY: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-opentelekomcloud-go: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-vault/actions/secrets/GO_GITHUB_TOKEN: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-cloudflare-go: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-googlebeta/labels/automerge: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-random/actions/secrets/NPM_TOKEN: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-helm/actions/secrets/GH_TOKEN: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-upcloud/actions/secrets/ALERT_PRS_SLACK_WEBHOOK_URL: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-gitlab/actions/secrets/NUGET_API_KEY: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-null-go: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-time/actions/secrets/NPM_TOKEN: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-snowflake/actions/secrets/MAVEN_USERNAME: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-databricks/actions/secrets/MAVEN_PASSWORD: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
╷
│ Error: GET https://api.github.com/repos/cdktf/cdktf-provider-local/hooks/387362838: 403 API rate limit of 5000 still exceeded until 2023-09-01 10:28:37 +0000 UTC, not making remote request. [rate reset in 14m16s]
│ 
│ 
╵
Operation failed: failed running terraform plan (exit 1)
::debug::Terraform exited with code 1.
::debug::stderr: 
::debug::exitcode: 1
::error::Terraform exited with code 1.

```

</details>

*Pusher: @DanielMSchmidt, Action: `pull_request`, Working Directory: ``, Workflow: `Plan`*

2023-09-01 10:39 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-WUpnPZzeBudvaod7" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/1dac92e5-0b29-49f7-846a-55c7e208521a/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-WUpnPZzeBudvaod7

Waiting for the plan to start...

Terraform v1.3.3
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
github_repository.customconstructs_cdktftfmodulestackgo_repo_BD5C70DA: Refreshing state... [id=cdktf-tf-module-stack-go]
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 0s [id=cdktf-multi-stack-tfe]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secrettwineusername_EB85F0BF: Refreshing state... [id=cdktf-multi-stack-tfe:TWINE_USERNAME]
github_repository_webhook.customconstructs_cdktfconstructcdktfmultistacktfe_repositorysetup_slackwebhook_B53BE4E1: Refreshing state... [id=385811467]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtoken_39B01FBC: Refreshing state... [id=cdktf-multi-stack-tfe:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretnpmtoken_53CDDEEA: Refreshing state... [id=cdktf-multi-stack-tfe:NPM_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secrettwinepassword_4FFE9BE5: Refreshing state... [id=cdktf-multi-stack-tfe:TWINE_PASSWORD]
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 0s [id=cdktf-tf-module-stack]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtokenaliasGOGITHUBTOKEN_5FC8E998: Refreshing state... [id=cdktf-multi-stack-tfe:GO_GITHUB_TOKEN]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 1s [id=cdktf-local-exec]
github_issue_label.customconstructs_cdktfconstructcdktfmultistacktfe_repositorysetup_automergelabel_81A2BE1F: Refreshing state... [id=cdktf-multi-stack-tfe:automerge]
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 1s [id=cdktf-cdk8s]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtokenaliasPROJENGITHUBTOKEN_26864905: Refreshing state... [id=cdktf-multi-stack-tfe:PROJEN_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavengpgprivatekey_C5913362: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_GPG_PRIVATE_KEY]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenpassword_11FCA788: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secrettwineusername_1ECAAABA: Refreshing state... [id=cdktf-tf-module-stack:TWINE_USERNAME]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavengpgprivatekeypassphrase_809F3B9E: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretnugetapikey_784194A7: Refreshing state... [id=cdktf-tf-module-stack:NUGET_API_KEY]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtokenaliasGOGITHUBTOKEN_E2D82A8A: Refreshing state... [id=cdktf-tf-module-stack:GO_GITHUB_TOKEN]
github_issue_label.customconstructs_cdktfconstructcdktftfmodulestack_repositorysetup_automergelabel_9EDDC355: Refreshing state... [id=cdktf-tf-module-stack:automerge]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secrettwinepassword_75B44DAA: Refreshing state... [id=cdktf-tf-module-stack:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenstagingprofileid_8A4652D8: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_STAGING_PROFILE_ID]
github_repository_webhook.customconstructs_cdktfconstructcdktftfmodulestack_repositorysetup_slackwebhook_62030303: Refreshing state... [id=385811493]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretnpmtoken_DF590CDA: Refreshing state... [id=cdktf-tf-module-stack:NPM_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtokenaliasPROJENGITHUBTOKEN_B560FB58: Refreshing state... [id=cdktf-tf-module-stack:PROJEN_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtoken_0F81B431: Refreshing state... [id=cdktf-tf-module-stack:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenusername_8940B1E6: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_USERNAME]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secrettwinepassword_01F20187: Refreshing state... [id=cdktf-local-exec:TWINE_PASSWORD]
data.github_team.cdktf-team-cdktf: Read complete after 5s [id=6602018]
github_repository_webhook.customconstructs_cdktfconstructcdktflocalexec_repositorysetup_slackwebhook_AD39C2ED: Refreshing state... [id=385811432]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretnpmtoken_C8A5F85E: Refreshing state... [id=cdktf-local-exec:NPM_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtoken_74A03037: Refreshing state... [id=cdktf-local-exec:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secrettwineusername_F630C71D: Refreshing state... [id=cdktf-local-exec:TWINE_USERNAME]
github_issue_label.customconstructs_cdktfconstructcdktflocalexec_repositorysetup_automergelabel_D60459FC: Refreshing state... [id=cdktf-local-exec:automerge]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtokenaliasGOGITHUBTOKEN_CF3E4145: Refreshing state... [id=cdktf-local-exec:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtokenaliasPROJENGITHUBTOKEN_AAB6222D: Refreshing state... [id=cdktf-local-exec:PROJEN_GITHUB_TOKEN]
github_issue_label.customconstructs_cdktfconstructcdktfcdk8s_repositorysetup_automergelabel_F24CD948: Refreshing state... [id=cdktf-cdk8s:automerge]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtokenaliasGOGITHUBTOKEN_685F1BFC: Refreshing state... [id=cdktf-cdk8s:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretnpmtoken_E84D4D40: Refreshing state... [id=cdktf-cdk8s:NPM_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtoken_15793D0C: Refreshing state... [id=cdktf-cdk8s:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secrettwinepassword_3EEB468D: Refreshing state... [id=cdktf-cdk8s:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtokenaliasPROJENGITHUBTOKEN_E3B90B5F: Refreshing state... [id=cdktf-cdk8s:PROJEN_GITHUB_TOKEN]
github_repository_webhook.customconstructs_cdktfconstructcdktfcdk8s_repositorysetup_slackwebhook_5D29CDDD: Refreshing state... [id=385811429]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secrettwineusername_2CE61A73: Refreshing state... [ [...]

2023-09-01 10:39 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-P4tCBnJqxVsEjwcx" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/d4e0ec36-a7c0-481c-b904-4853f7e66d2e/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-P4tCBnJqxVsEjwcx

Waiting for the plan to start...

Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
github_repository.repospartners_cdktfprovidermongodbatlas_repo_B439CDB5: Refreshing state... [id=cdktf-provider-mongodbatlas]
github_repository.repospartners_cdktfproviderlaunchdarklygo_repo_C9F0819B: Refreshing state... [id=cdktf-provider-launchdarkly-go]
github_repository.repospartners_cdktfprovidermongodbatlasgo_repo_718CC063: Refreshing state... [id=cdktf-provider-mongodbatlas-go]
github_repository.repospartners_cdktfproviderlaunchdarkly_repo_AF3BB314: Refreshing state... [id=cdktf-provider-launchdarkly]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenstagingprofileid_ACEFEFB8: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_STAGING_PROFILE_ID]
github_branch_protection.repospartners_cdktfprovidermongodbatlas_repositorysetup_mainprotection_D2492D82: Refreshing state... [id=BPR_kwDOI2liXc4CAYbG]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretnpmtoken_065C759D: Refreshing state... [id=cdktf-provider-mongodbatlas:NPM_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtoken_E25B0748: Refreshing state... [id=cdktf-provider-mongodbatlas:GH_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenusername_FEB58691: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_USERNAME]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretnugetapikey_F529A53B: Refreshing state... [id=cdktf-provider-mongodbatlas:NUGET_API_KEY]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenpassword_B7E76303: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_PASSWORD]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavengpgprivatekeypassphrase_1A7C8C8A: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secrettwinepassword_0017705E: Refreshing state... [id=cdktf-provider-mongodbatlas:TWINE_PASSWORD]
data.github_team.cdktf-team-cdktf: Read complete after 3s [id=6602018]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtokenaliasPROJENGITHUBTOKEN_C1B036A4: Refreshing state... [id=cdktf-provider-mongodbatlas:PROJEN_GITHUB_TOKEN]
github_repository_webhook.repospartners_cdktfprovidermongodbatlas_repositorysetup_slackwebhook_9D8453CA: Refreshing state... [id=398580582]
github_issue_label.repospartners_cdktfprovidermongodbatlas_repositorysetup_automergelabel_3E161F2F: Refreshing state... [id=cdktf-provider-mongodbatlas:automerge]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secrettwineusername_BB8420B9: Refreshing state... [id=cdktf-provider-mongodbatlas:TWINE_USERNAME]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtokenaliasGOGITHUBTOKEN_7F93E828: Refreshing state... [id=cdktf-provider-mongodbatlas:GO_GITHUB_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretalertprsslackwebhookurl_27DBACFE: Refreshing state... [id=cdktf-provider-mongodbatlas:ALERT_PRS_SLACK_WEBHOOK_URL]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavengpgprivatekey_95F35FFB: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_GPG_PRIVATE_KEY]
github_issue_label.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_automergelabel_35291F2B: Refreshing state... [id=cdktf-provider-launchdarkly-go:automerge]
github_repository_webhook.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_slackwebhook_E7459C6F: Refreshing state... [id=425871230]
github_issue_label.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_automergelabel_B7FEA225: Refreshing state... [id=cdktf-provider-mongodbatlas-go:automerge]
github_repository_webhook.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_slackwebhook_18FFF8DE: Refreshing state... [id=398580580]
github_branch_protection.repospartners_cdktfproviderlaunchdarkly_repositorysetup_mainprotection_275B3DCB: Refreshing state... [id=BPR_kwDOJ_5BQc4CYBOl]
github_repository_webhook.repospartners_cdktfproviderlaunchdarkly_repositorysetup_slackwebhook_9AD3D6AF: Refreshing state... [id=425871226]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretnugetapikey_A8CFC2DD: Refreshing state... [id=cdktf-provider-launchdarkly:NUGET_API_KEY]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secrettwineusername_EC15FA2E: Refreshing state... [id=cdktf-provider-launchdarkly:TWINE_USERNAME]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavengpgprivatekeypassphrase_416CB401: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretnpmtoken_55C9B1E4: Refreshing state... [id=cdktf-provider-launchdarkly:NPM_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secrettwinepassword_F4217409: Refreshing state... [id=cdktf-provider-launchdarkly:TWINE_PASSWORD]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavengpgprivatekey_43CD5933: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_GPG_PRIVATE_KEY]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretalertprsslackwebhookurl_99526CD8: Refreshing state... [id=cdktf-provider-launchdarkly:ALERT_PRS_SLACK_WEBHOOK_URL]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenstagingprofileid_919B2A41: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_STAGING_PROFILE_ID]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtokenaliasPROJENGITHUBTOKEN_D014A00B: Refreshing state... [id=cdktf-provider-launchdarkly:PROJEN_GITHUB_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenusername_6CBB637A: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_USERNAME]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtoken_B076E5A5: Refreshing state... [id=cdktf-provider-launchdarkly:GH_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenpassword_B811F8CB: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_PASSWORD]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtokenaliasGOGITHUBTOKEN_E643F160: Refreshing state... [id=cdktf-provider-launchdarkly:GO_GITHUB_TOKEN]
github_issue_label.repospartners_cdktfproviderlaunchdarkly_repositorysetup_automergelabel_0E78197D: Refreshing state... [id=cdktf-provider-launchdarkly:automerge]
github_team_repository.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_managingteam_24105904: Refreshing state... [id=6602018:cdktf-provider-mongodbatlas-go]
github_team_repository.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_managingteam_7D3BC365: Refreshing state... [id=6602018:cdktf-provider-launchdarkly-go]
github_team_repository.repospartners_cdktfprovidermongodbatlas_repositorysetup_managingteam_0804D53A: Refreshing state... [id=6602018:cdktf-provider-mongodbatlas]
github_team_repository.repospartners_cdktfproviderlaunchdarkly_repositorysetup_managingteam_B55490C8:  [...]

2023-09-01 10:40 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-q8RapvyTc1hkJXwv" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/7bd12c0d-d457-4a09-a2c6-231a0c99fef3/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-q8RapvyTc1hkJXwv

Waiting for the plan to start...

Terraform v1.3.1
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 6s [id=6602018]

Changes to Outputs:
  + providerRepos                           = [
      + "github_repository.reposofficialnew_cdktfproviderad_repo_B501EA48.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderazurestack_repo_F02F6EBF.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderboundary_repo_1EF8E2A8.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderconsul_repo_EA05D767.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderdns_repo_E696C338.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidergoogleworkspace_repo_DC6187AE.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhcp_repo_BAD7E858.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhcs_repo_1C1956F4.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhttp_repo_0228697D.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidernomad_repo_E3E08A10.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovideropc_repo_36585570.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovideroraclepaas_repo_59E01823.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidersalesforce_repo_00119DDA.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidervsphere_repo_AD726BE1.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderwaypoint_repo_88065F9C.ssh_clone_url",
    ]
  - reposofficialnew_providerRepos_9F1CE2EB = [
      - "git@github.com:cdktf/cdktf-provider-ad.git",
      - "git@github.com:cdktf/cdktf-provider-azurestack.git",
      - "git@github.com:cdktf/cdktf-provider-boundary.git",
      - "git@github.com:cdktf/cdktf-provider-consul.git",
      - "git@github.com:cdktf/cdktf-provider-dns.git",
      - "git@github.com:cdktf/cdktf-provider-googleworkspace.git",
      - "git@github.com:cdktf/cdktf-provider-hcp.git",
      - "git@github.com:cdktf/cdktf-provider-hcs.git",
      - "git@github.com:cdktf/cdktf-provider-http.git",
      - "git@github.com:cdktf/cdktf-provider-nomad.git",
      - "git@github.com:cdktf/cdktf-provider-opc.git",
      - "git@github.com:cdktf/cdktf-provider-oraclepaas.git",
      - "git@github.com:cdktf/cdktf-provider-salesforce.git",
      - "git@github.com:cdktf/cdktf-provider-vsphere.git",
      - "git@github.com:cdktf/cdktf-provider-waypoint.git",
    ] -> null

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
::debug::Terraform exited with code 0.
::debug::stderr: 
::debug::exitcode: 0

```

</details>

*Pusher: @DanielMSchmidt, Action: `pull_request`, Working Directory: ``, Workflow: `Plan`*

2023-09-01 10:42 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-Dtz5Np9KuYPUenAC" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/d2647780-79f1-4e5e-851d-1caacf83e519/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-Dtz5Np9KuYPUenAC

Waiting for the plan to start...

Terraform v1.0.7
on linux_amd64
Initializing plugins and modules...

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # github_team_repository.repos_cdktfproviderpagerduty_repositorysetup_managingteam_BBF13F0C has been changed
  ~ resource "github_team_repository" "repos_cdktfproviderpagerduty_repositorysetup_managingteam_BBF13F0C" {
      ~ etag       = "W/\"922cca933ca0fb257774bd9cf9de45a1384b444594b519965488a340147a52f6\"" -> "W/\"a36a6bd117b3000ce07fb9cf64c2f9a6d559b55d338ce9a5f8a717c60a4156ac\""
        id         = "6602018:cdktf-provider-pagerduty"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfprovidertemplatego_repositorysetup_automergelabel_DFBF9CCC has been changed
  ~ resource "github_issue_label" "repos_cdktfprovidertemplatego_repositorysetup_automergelabel_DFBF9CCC" {
      ~ etag       = "W/\"a7780e2ee15aa18d2c6ac8f9ad0560070c55a63bf60bd5ed1368d1737c66e649\"" -> "W/\"a2287096b6ebb9f57c724e34b6ea214aea9fe15876639057ffb0b9cd5ef7ab4c\""
        id         = "cdktf-provider-template-go:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfproviderazuread_repositorysetup_automergelabel_FF64E4A9 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderazuread_repositorysetup_automergelabel_FF64E4A9" {
      ~ etag       = "W/\"13067b688fb36329fdc5afaeb42429e73a161f642cabfde9dc095591fa5b1967\"" -> "W/\"eece02ad31c74ca9cf86b3b250fc38d8b5dec19efd6377c9559c640e57460479\""
        id         = "cdktf-provider-azuread:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderrandom_repo_448077DE has been changed
  ~ resource "github_repository" "repos_cdktfproviderrandom_repo_448077DE" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"6704d98249ad2a3e7f9d001dfc08cad8f68e839a89e1e4fc0adbecb0c71b57a5\"" -> "W/\"390659154e79f966aa0725a93edb7dfff76d7c9635994d0cc9c5c9a38d31c53b\""
      + has_discussions             = false
        id                          = "cdktf-provider-random"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-random"
      + primary_language            = "TypeScript"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_issue_label.repos_cdktfprovidergooglebeta_repositorysetup_automergelabel_BE75E014 has been changed
  ~ resource "github_issue_label" "repos_cdktfprovidergooglebeta_repositorysetup_automergelabel_BE75E014" {
      ~ etag       = "W/\"7659a325d73b080d791ab7de23c3e03f7106470ada6be5b25239fa709657a8dd\"" -> "W/\"b21a162a284351d6d3502c5c15ac266527bc5f326291c76bd5f52b2431c4464d\""
        id         = "cdktf-provider-googlebeta:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_repository.repos_cdktfproviderdnsimple_repo_6389F145 has been changed
  ~ resource "github_repository" "repos_cdktfproviderdnsimple_repo_6389F145" {
      + allow_auto_merge            = false
      + allow_update_branch         = false
      ~ etag                        = "W/\"aa574449b724c882a9b672c7a7579ed65e9b21c036480a9dea42590a7f367471\"" -> "W/\"2cc51d43d19d89de5073d0126dc4bbd99dadbc778c34ed5881c4f7a1bfec4ea8\""
      + has_discussions             = false
        id                          = "cdktf-provider-dnsimple"
      + merge_commit_message        = "PR_TITLE"
      + merge_commit_title          = "MERGE_MESSAGE"
        name                        = "cdktf-provider-dnsimple"
      + primary_language            = "TypeScript"
      + squash_merge_commit_message = "COMMIT_MESSAGES"
      + squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        # (26 unchanged attributes hidden)

      + security_and_analysis {

          + secret_scanning {
              + status = "disabled"
            }

          + secret_scanning_push_protection {
              + status = "disabled"
            }
        }
    }
  # github_branch_protection.repos_cdktfproviderionoscloud_repositorysetup_mainprotection_E5F3E21A has been changed
  ~ resource "github_branch_protection" "repos_cdktfproviderionoscloud_repositorysetup_mainprotection_E5F3E21A" {
      + blocks_creations                = false
      + force_push_bypassers            = []
        id                              = "BPR_kwDOHF6eps4B07vZ"
      + lock_branch                     = false
      + require_conversation_resolution = false
      + required_linear_history         = false
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
  # github_issue_label.repos_cdktfprovidervault_repositorysetup_automergelabel_7D646C91 has been changed
  ~ resource "github_issue_label" "repos_cdktfprovidervault_repositorysetup_automergelabel_7D646C91" {
      ~ etag       = "W/\"c76c3c0469ff5b5c43844f3665a29073045381d1237423912be1a32b10a89613\"" -> "W/\"9aaa868f0f37d9a4313d7f0728aeaf5a885f983af53055e969e27e969c1b9b27\""
        id         = "cdktf-provider-vault:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_issue_label.repos_cdktfproviderarchive_repositorysetup_automergelabel_5CF85AC3 has been changed
  ~ resource "github_issue_label" "repos_cdktfproviderarchive_repositorysetup_automergelabel_5CF85AC3" {
      ~ etag       = "W/\"3233ec41d86ebdaa348871c93accbcdd2c26f046f74070cc04f3e4493efa6a1a\"" -> "W/\"f1cae91fdf5b3129371e1c1bc395c661e9794ea2c1142b814ba588ed965bf229\""
        id         = "cdktf-provider-archive:automerge"
        name       = "automerge"
        # (3 unchanged attributes hidden)
    }
  # github_branch_protection.repos_cdktfprovidertime_repositorysetup_mainprotection_A7571876 has been changed
  ~ resource "github_branch_protection" "repos_cdktfprovidertime_repositorysetup_mainprotection_A7571876" {
      + blocks_creations                = false
      + force_push_bypassers            = []
        id                              = "BPR_kwDOHfp-Z84B07w1"
      + lock_branch                     = false
      + require_conversation_resolution = false
      + required_linear_history         = false
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
  # github_branch_protection.repos_cdktfprovidergoogle_repositorysetup_mainprotection_6BA127EB has been changed
  ~ resource "github_branch_protection" "repos_cdktfprovidergoogle_repositorysetup_mainprotection_6BA127EB" {
      + blocks_creations                = false
      + force_push_bypassers            = []
        id                              = "BPR_kwDOERTEdc4B07uR"
      + lock_branch                     = false
      + require_conversation_resolution = false
      + required_linear_history [...]

2023-09-06 11:36 UTC, mutahhir approved these changes
Nice! FYI, I also updated the TF workspaces to have the 1.4.6 Terraform version on the workspaces themselves.

2023-09-07 14:14 UTC, ansgarm approved these changes

2023-09-07 15:04 UTC, team-tf-cdk commented
#### [`custom-constructs`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-Hp9HDPRAjsDyTdzK" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/0af41fb8-60d5-43d2-b0ff-55fed22f34a9/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/custom-constructs/runs/run-Hp9HDPRAjsDyTdzK

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Reading...
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Reading...
data.github_team.cdktf-team-cdktf: Reading...
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Reading...
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Reading...
github_repository.customconstructs_cdktftfmodulestackgo_repo_BD5C70DA: Refreshing state... [id=cdktf-tf-module-stack-go]
data.github_repository.cdktf-construct-cdktf-multi-stack-tfe_repo_5BB71C62: Read complete after 0s [id=cdktf-multi-stack-tfe]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secrettwinepassword_4FFE9BE5: Refreshing state... [id=cdktf-multi-stack-tfe:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretnpmtoken_53CDDEEA: Refreshing state... [id=cdktf-multi-stack-tfe:NPM_TOKEN]
github_repository_webhook.customconstructs_cdktfconstructcdktfmultistacktfe_repositorysetup_slackwebhook_B53BE4E1: Refreshing state... [id=385811467]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtokenaliasPROJENGITHUBTOKEN_26864905: Refreshing state... [id=cdktf-multi-stack-tfe:PROJEN_GITHUB_TOKEN]
github_issue_label.customconstructs_cdktfconstructcdktfmultistacktfe_repositorysetup_automergelabel_81A2BE1F: Refreshing state... [id=cdktf-multi-stack-tfe:automerge]
data.github_repository.cdktf-construct-cdktf-cdk8s_repo_6A622B5E: Read complete after 0s [id=cdktf-cdk8s]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtoken_39B01FBC: Refreshing state... [id=cdktf-multi-stack-tfe:GH_TOKEN]
data.github_repository.cdktf-construct-cdktf-local-exec_repo_64EDC49D: Read complete after 0s [id=cdktf-local-exec]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secrettwineusername_EB85F0BF: Refreshing state... [id=cdktf-multi-stack-tfe:TWINE_USERNAME]
data.github_repository.cdktf-construct-cdktf-tf-module-stack_repo_1C630C5A: Read complete after 1s [id=cdktf-tf-module-stack]
github_actions_secret.customconstructs_cdktfconstructcdktfmultistacktfe_repo_secretghtokenaliasGOGITHUBTOKEN_5FC8E998: Refreshing state... [id=cdktf-multi-stack-tfe:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtokenaliasPROJENGITHUBTOKEN_E3B90B5F: Refreshing state... [id=cdktf-cdk8s:PROJEN_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtokenaliasGOGITHUBTOKEN_685F1BFC: Refreshing state... [id=cdktf-cdk8s:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretghtoken_15793D0C: Refreshing state... [id=cdktf-cdk8s:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secretnpmtoken_E84D4D40: Refreshing state... [id=cdktf-cdk8s:NPM_TOKEN]
github_issue_label.customconstructs_cdktfconstructcdktfcdk8s_repositorysetup_automergelabel_F24CD948: Refreshing state... [id=cdktf-cdk8s:automerge]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secrettwinepassword_3EEB468D: Refreshing state... [id=cdktf-cdk8s:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktfcdk8s_repo_secrettwineusername_2CE61A73: Refreshing state... [id=cdktf-cdk8s:TWINE_USERNAME]
github_repository_webhook.customconstructs_cdktfconstructcdktfcdk8s_repositorysetup_slackwebhook_5D29CDDD: Refreshing state... [id=385811429]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtoken_74A03037: Refreshing state... [id=cdktf-local-exec:GH_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtokenaliasGOGITHUBTOKEN_CF3E4145: Refreshing state... [id=cdktf-local-exec:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secrettwinepassword_01F20187: Refreshing state... [id=cdktf-local-exec:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secrettwineusername_F630C71D: Refreshing state... [id=cdktf-local-exec:TWINE_USERNAME]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretnpmtoken_C8A5F85E: Refreshing state... [id=cdktf-local-exec:NPM_TOKEN]
github_issue_label.customconstructs_cdktfconstructcdktflocalexec_repositorysetup_automergelabel_D60459FC: Refreshing state... [id=cdktf-local-exec:automerge]
github_repository_webhook.customconstructs_cdktfconstructcdktflocalexec_repositorysetup_slackwebhook_AD39C2ED: Refreshing state... [id=385811432]
github_actions_secret.customconstructs_cdktfconstructcdktflocalexec_repo_secretghtokenaliasPROJENGITHUBTOKEN_AAB6222D: Refreshing state... [id=cdktf-local-exec:PROJEN_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secrettwineusername_1ECAAABA: Refreshing state... [id=cdktf-tf-module-stack:TWINE_USERNAME]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenstagingprofileid_8A4652D8: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_STAGING_PROFILE_ID]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secrettwinepassword_75B44DAA: Refreshing state... [id=cdktf-tf-module-stack:TWINE_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenpassword_11FCA788: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_PASSWORD]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtokenaliasGOGITHUBTOKEN_E2D82A8A: Refreshing state... [id=cdktf-tf-module-stack:GO_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtokenaliasPROJENGITHUBTOKEN_B560FB58: Refreshing state... [id=cdktf-tf-module-stack:PROJEN_GITHUB_TOKEN]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavengpgprivatekey_C5913362: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_GPG_PRIVATE_KEY]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretnpmtoken_DF590CDA: Refreshing state... [id=cdktf-tf-module-stack:NPM_TOKEN]
data.github_team.cdktf-team-cdktf: Read complete after 8s [id=6602018]
github_repository_webhook.customconstructs_cdktfconstructcdktftfmodulestack_repositorysetup_slackwebhook_62030303: Refreshing state... [id=385811493]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretnugetapikey_784194A7: Refreshing state... [id=cdktf-tf-module-stack:NUGET_API_KEY]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavenusername_8940B1E6: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_USERNAME]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretmavengpgprivatekeypassphrase_809F3B9E: Refreshing state... [id=cdktf-tf-module-stack:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
github_issue_label.customconstructs_cdktfconstructcdktftfmodulestack_repositorysetup_automergelabel_9EDDC355: Refreshing state... [id=cdktf-tf-module-stack:automerge]
github_actions_secret.customconstructs_cdktfconstructcdktftfmodulestack_repo_secretghtoken_0F81B431: Refreshing state... [id=c [...]

2023-09-07 15:05 UTC, team-tf-cdk commented
#### [`repos-partners`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-AkezjDgt1xuGNc2e" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/a7403af1-d3ee-4769-9a4b-2047a1bfd1e0/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-partners/runs/run-AkezjDgt1xuGNc2e

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
github_repository.repospartners_cdktfprovidermongodbatlasgo_repo_718CC063: Refreshing state... [id=cdktf-provider-mongodbatlas-go]
github_repository.repospartners_cdktfprovidermongodbatlas_repo_B439CDB5: Refreshing state... [id=cdktf-provider-mongodbatlas]
github_repository.repospartners_cdktfproviderlaunchdarkly_repo_AF3BB314: Refreshing state... [id=cdktf-provider-launchdarkly]
github_repository.repospartners_cdktfproviderlaunchdarklygo_repo_C9F0819B: Refreshing state... [id=cdktf-provider-launchdarkly-go]
github_issue_label.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_automergelabel_35291F2B: Refreshing state... [id=cdktf-provider-launchdarkly-go:automerge]
github_repository_webhook.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_slackwebhook_E7459C6F: Refreshing state... [id=425871230]
github_issue_label.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_automergelabel_B7FEA225: Refreshing state... [id=cdktf-provider-mongodbatlas-go:automerge]
github_repository_webhook.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_slackwebhook_18FFF8DE: Refreshing state... [id=398580580]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenusername_FEB58691: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_USERNAME]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtokenaliasPROJENGITHUBTOKEN_C1B036A4: Refreshing state... [id=cdktf-provider-mongodbatlas:PROJEN_GITHUB_TOKEN]
github_repository_webhook.repospartners_cdktfprovidermongodbatlas_repositorysetup_slackwebhook_9D8453CA: Refreshing state... [id=398580582]
github_issue_label.repospartners_cdktfprovidermongodbatlas_repositorysetup_automergelabel_3E161F2F: Refreshing state... [id=cdktf-provider-mongodbatlas:automerge]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secrettwineusername_BB8420B9: Refreshing state... [id=cdktf-provider-mongodbatlas:TWINE_USERNAME]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretnpmtoken_065C759D: Refreshing state... [id=cdktf-provider-mongodbatlas:NPM_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenstagingprofileid_ACEFEFB8: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_STAGING_PROFILE_ID]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtokenaliasGOGITHUBTOKEN_7F93E828: Refreshing state... [id=cdktf-provider-mongodbatlas:GO_GITHUB_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretnugetapikey_F529A53B: Refreshing state... [id=cdktf-provider-mongodbatlas:NUGET_API_KEY]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavengpgprivatekey_95F35FFB: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_GPG_PRIVATE_KEY]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secrettwinepassword_0017705E: Refreshing state... [id=cdktf-provider-mongodbatlas:TWINE_PASSWORD]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretghtoken_E25B0748: Refreshing state... [id=cdktf-provider-mongodbatlas:GH_TOKEN]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretalertprsslackwebhookurl_27DBACFE: Refreshing state... [id=cdktf-provider-mongodbatlas:ALERT_PRS_SLACK_WEBHOOK_URL]
github_branch_protection.repospartners_cdktfprovidermongodbatlas_repositorysetup_mainprotection_D2492D82: Refreshing state... [id=BPR_kwDOI2liXc4CAYbG]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavenpassword_B7E76303: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_PASSWORD]
github_actions_secret.repospartners_cdktfprovidermongodbatlas_repo_secretmavengpgprivatekeypassphrase_1A7C8C8A: Refreshing state... [id=cdktf-provider-mongodbatlas:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
data.github_team.cdktf-team-cdktf: Read complete after 6s [id=6602018]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavengpgprivatekey_43CD5933: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_GPG_PRIVATE_KEY]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavengpgprivatekeypassphrase_416CB401: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_GPG_PRIVATE_KEY_PASSPHRASE]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtokenaliasPROJENGITHUBTOKEN_D014A00B: Refreshing state... [id=cdktf-provider-launchdarkly:PROJEN_GITHUB_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretalertprsslackwebhookurl_99526CD8: Refreshing state... [id=cdktf-provider-launchdarkly:ALERT_PRS_SLACK_WEBHOOK_URL]
github_issue_label.repospartners_cdktfproviderlaunchdarkly_repositorysetup_automergelabel_0E78197D: Refreshing state... [id=cdktf-provider-launchdarkly:automerge]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenusername_6CBB637A: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_USERNAME]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secrettwineusername_EC15FA2E: Refreshing state... [id=cdktf-provider-launchdarkly:TWINE_USERNAME]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secrettwinepassword_F4217409: Refreshing state... [id=cdktf-provider-launchdarkly:TWINE_PASSWORD]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretnpmtoken_55C9B1E4: Refreshing state... [id=cdktf-provider-launchdarkly:NPM_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenpassword_B811F8CB: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_PASSWORD]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretnugetapikey_A8CFC2DD: Refreshing state... [id=cdktf-provider-launchdarkly:NUGET_API_KEY]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtoken_B076E5A5: Refreshing state... [id=cdktf-provider-launchdarkly:GH_TOKEN]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretghtokenaliasGOGITHUBTOKEN_E643F160: Refreshing state... [id=cdktf-provider-launchdarkly:GO_GITHUB_TOKEN]
github_repository_webhook.repospartners_cdktfproviderlaunchdarkly_repositorysetup_slackwebhook_9AD3D6AF: Refreshing state... [id=425871226]
github_branch_protection.repospartners_cdktfproviderlaunchdarkly_repositorysetup_mainprotection_275B3DCB: Refreshing state... [id=BPR_kwDOJ_5BQc4CYBOl]
github_actions_secret.repospartners_cdktfproviderlaunchdarkly_repo_secretmavenstagingprofileid_919B2A41: Refreshing state... [id=cdktf-provider-launchdarkly:MAVEN_STAGING_PROFILE_ID]
github_team_repository.repospartners_cdktfprovidermongodbatlasgo_repositorysetup_managingteam_24105904: Refreshing state... [id=6602018:cdktf-provider-mongodbatlas-go]
github_team_repository.repospartners_cdktfproviderlaunchdarklygo_repositorysetup_managingteam_7D3BC365: Refreshing state... [id=6602018:cdktf-provider-launchdarkly-go]
github_team_repository.repospartners_cdktfproviderlaunchdarkly_repositorysetup_managingteam_B55490C8: Refreshing state... [id=6602018:cdktf-provider-launchdarkly]
github_team_repository.repospartners_cdktfprovidermongodbatlas_repositorysetup_managingteam_0804D53A:  [...]

2023-09-07 15:06 UTC, team-tf-cdk commented
#### [`repos-official-new`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-Cv5pQ8FurNjqELgf" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/f2729bd0-81b9-476f-b718-415d068404c0/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers-official-new/runs/run-Cv5pQ8FurNjqELgf

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 10s [id=6602018]

Changes to Outputs:
  + providerRepos                           = [
      + "github_repository.reposofficialnew_cdktfproviderad_repo_B501EA48.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderazurestack_repo_F02F6EBF.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderboundary_repo_1EF8E2A8.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderconsul_repo_EA05D767.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderdns_repo_E696C338.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidergoogleworkspace_repo_DC6187AE.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhcp_repo_BAD7E858.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhcs_repo_1C1956F4.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderhttp_repo_0228697D.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidernomad_repo_E3E08A10.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovideropc_repo_36585570.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovideroraclepaas_repo_59E01823.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidersalesforce_repo_00119DDA.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfprovidervsphere_repo_AD726BE1.ssh_clone_url",
      + "github_repository.reposofficialnew_cdktfproviderwaypoint_repo_88065F9C.ssh_clone_url",
    ]
  - reposofficialnew_providerRepos_9F1CE2EB = [
      - "git@github.com:cdktf/cdktf-provider-ad.git",
      - "git@github.com:cdktf/cdktf-provider-azurestack.git",
      - "git@github.com:cdktf/cdktf-provider-boundary.git",
      - "git@github.com:cdktf/cdktf-provider-consul.git",
      - "git@github.com:cdktf/cdktf-provider-dns.git",
      - "git@github.com:cdktf/cdktf-provider-googleworkspace.git",
      - "git@github.com:cdktf/cdktf-provider-hcp.git",
      - "git@github.com:cdktf/cdktf-provider-hcs.git",
      - "git@github.com:cdktf/cdktf-provider-http.git",
      - "git@github.com:cdktf/cdktf-provider-nomad.git",
      - "git@github.com:cdktf/cdktf-provider-opc.git",
      - "git@github.com:cdktf/cdktf-provider-oraclepaas.git",
      - "git@github.com:cdktf/cdktf-provider-salesforce.git",
      - "git@github.com:cdktf/cdktf-provider-vsphere.git",
      - "git@github.com:cdktf/cdktf-provider-waypoint.git",
    ] -> null

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
::debug::Terraform exited with code 0.
::debug::stderr: 
::debug::exitcode: 0

```

</details>

*Pusher: @DanielMSchmidt, Action: `pull_request`, Working Directory: ``, Workflow: `Plan`*

2023-09-07 15:07 UTC, team-tf-cdk commented
#### [`repos`] Terraform Plan 📖`success`

<a href="https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-F89WyzchGSk1upvu" target="_blank">Remote Plan Link ↗️</a>

<details><summary>Show Plan</summary>

```tf
[command]/home/runner/work/_temp/02ec87b4-323e-402b-86ba-68f827b007db/terraform-bin plan -no-color
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/cdktf-team/prebuilt-providers/runs/run-F89WyzchGSk1upvu

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.github_team.cdktf-team-cdktf: Reading...
data.github_team.cdktf-team-cdktf: Read complete after 8s [id=6602018]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_repository.repos_cdktfproviderarchive_repo_F28A4A49 will be updated in-place
  ~ resource "github_repository" "repos_cdktfproviderarchive_repo_F28A4A49" {
      ~ allow_auto_merge            = true -> false
        id                          = "cdktf-provider-archive"
        name                        = "cdktf-provider-archive"
        # (34 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # github_repository.repos_cdktfproviderdocker_repo_45A47809 will be updated in-place
  ~ resource "github_repository" "repos_cdktfproviderdocker_repo_45A47809" {
      ~ allow_auto_merge            = true -> false
        id                          = "cdktf-provider-docker"
        name                        = "cdktf-provider-docker"
        # (34 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # github_repository.repos_cdktfprovidernull_repo_8A692B1D will be updated in-place
  ~ resource "github_repository" "repos_cdktfprovidernull_repo_8A692B1D" {
      ~ allow_auto_merge            = true -> false
        id                          = "cdktf-provider-null"
        name                        = "cdktf-provider-null"
        # (34 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # github_repository.repos_cdktfproviderpagerduty_repo_0AF36FE3 will be updated in-place
  ~ resource "github_repository" "repos_cdktfproviderpagerduty_repo_0AF36FE3" {
      ~ allow_auto_merge            = true -> false
        id                          = "cdktf-provider-pagerduty"
        name                        = "cdktf-provider-pagerduty"
        # (34 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # github_repository.repos_cdktfproviderproject_repo_014C3CE2 will be updated in-place
  ~ resource "github_repository" "repos_cdktfproviderproject_repo_014C3CE2" {
      ~ allow_auto_merge            = true -> false
      - allow_update_branch         = true -> null
        id                          = "cdktf-provider-project"
        name                        = "cdktf-provider-project"
      ~ squash_merge_commit_message = "PR_BODY" -> "COMMIT_MESSAGES"
      ~ squash_merge_commit_title   = "PR_TITLE" -> "COMMIT_OR_PR_TITLE"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # github_repository.repos_cdktfrepositorymanager_repo_9D19EE52 will be updated in-place
  ~ resource "github_repository" "repos_cdktfrepositorymanager_repo_9D19EE52" {
      ~ allow_auto_merge            = true -> false
      - allow_update_branch         = true -> null
        id                          = "cdktf-repository-manager"
        name                        = "cdktf-repository-manager"
      ~ squash_merge_commit_message = "PR_BODY" -> "COMMIT_MESSAGES"
      ~ squash_merge_commit_title   = "PR_TITLE" -> "COMMIT_OR_PR_TITLE"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 6 to change, 0 to destroy.

Changes to Outputs:
  + providerRepos                  = [
      + "github_repository.repos_cdktfprovideracme_repo_DD1AA41F.ssh_clone_url",
      + "github_repository.repos_cdktfproviderarchive_repo_F28A4A49.ssh_clone_url",
      + "github_repository.repos_cdktfprovideraws_repo_55F46B23.ssh_clone_url",
      + "github_repository.repos_cdktfproviderazuread_repo_A398ECE6.ssh_clone_url",
      + "github_repository.repos_cdktfproviderazurerm_repo_19E06DC3.ssh_clone_url",
      + "github_repository.repos_cdktfprovidercloudflare_repo_69763868.ssh_clone_url",
      + "github_repository.repos_cdktfprovidercloudinit_repo_4E4D12FF.ssh_clone_url",
      + "github_repository.repos_cdktfproviderdatabricks_repo_43A853E0.ssh_clone_url",
      + "github_repository.repos_cdktfproviderdatadog_repo_3C8DEE00.ssh_clone_url",
      + "github_repository.repos_cdktfproviderdigitalocean_repo_5200BE67.ssh_clone_url",
      + "github_repository.repos_cdktfproviderdocker_repo_45A47809.ssh_clone_url",
      + "github_repository.repos_cdktfproviderdnsimple_repo_6389F145.ssh_clone_url",
      + "github_repository.repos_cdktfproviderexternal_repo_2177D259.ssh_clone_url",
      + "github_repository.repos_cdktfprovidergithub_repo_66B8E54A.ssh_clone_url",
      + "github_repository.repos_cdktfprovidergitlab_repo_2ECAC2E4.ssh_clone_url",
      + "github_repository.repos_cdktfprovidergoogle_repo_3D7769E0.ssh_clone_url",
      + "github_repository.repos_cdktfprovidergooglebeta_repo_077561F9.ssh_clone_url",
      + "github_repository.repos_cdktfproviderhashicups_repo_DC950547.ssh_clone_url",
      + "github_repository.repos_cdktfproviderhelm_repo_E5C9B6C8.ssh_clone_url",
      + "github_repository.repos_cdktfproviderionoscloud_repo_38B54253.ssh_clone_url",
      + "github_repository.repos_cdktfproviderkubernetes_repo_D69C3A79.ssh_clone_url",
      + "github_repository.repos_cdktfproviderlocal_repo_4D7B21AD.ssh_clone_url",
      + "github_repository.repos_cdktfprovidernewrelic_repo_D84B1F73.ssh_clone_url",
      + "github_repository.repos_cdktfprovidernull_repo_8A692B1D.ssh_clone_url",
      + "github_repository.repos_cdktfproviderokta_repo_BB6AE56D.ssh_clone_url",
      + "github_repository.repos_cdktfprovideropentelekomcloud_repo_8ABA825B.ssh_clone_url",
      + "github_repository.repos_cdktfproviderpagerduty_repo_0AF36FE3.ssh_clone_url",
      + "github_repository.repos_cdktfproviderpostgresql_repo_9CD37AD7.ssh_clone_url",
      + "github_repository.repos_cdktfproviderrandom_repo_448077DE.ssh_clone_url",
      + "github_repository.repos_cdktfprovidersnowflake_repo_483928D8.ssh_clone_url",
      + "github_repository.repos_cdktfproviderspotinst_repo_AC5A9A96.ssh_clone_url",
      + "github_repository.repos_cdktfprovidertemplate_repo_08DFB684.ssh_clone_url",
      + "github_repository.repos_cdktfprovidertfe_repo_27B3A80F.ssh_clone_url",
      + "github_repository.repos_cdktfprovidertime_repo_35EDF4BB.ssh_clone_url",
      + "github_repository.repos_cdktfprovidertls_repo_E6EAEEBE.ssh_clone_url",
      + "github_repository.repos_cdktfproviderupcloud_repo_D37E7624.ssh_clone_url",
      + "github_repository.repos_cdktfprovidervault_repo_CDB996AE.ssh_clone_url",
    ]
  - repos_providerRepos_C7679B58   = [
      - "git@github.com:cdktf/cdktf-provider-acme.git",
      - "git@github.com:cdktf/cdktf-provider-archive.git",
      - "git@github.com:cdktf/cdktf-provider-aws.git",
      - "git@github.com:cdktf/cdktf-provider-azuread.git",
      - "git@github.com:cdktf/cdktf-provider-azurerm.git",
      - "git@github.com:cdktf/cdktf-provider-cloudflare.git",
      - "git@github.com:cdktf/cdktf-provider-cloudinit.git",
      - "git@github.com:cdktf/cdktf-provider-databricks.git",
      - "git@github.com:cdktf/cdktf-provider-datadog.git",
      - "git@github.com:cdktf/cdktf-provider-digitalocean.git",
      - "git@github.com:cdktf/cdktf-provider-docker.git",
      - "git@github.com:cdktf/cdktf-provider-dn [...]

2023-09-07 16:07 UTC, merged